'use strict'; 
var zon_config = {
"CONFIG_MAKEFLAGS": "DIST=APP RELEASE=y AUTO_SIGN=y CONFIG_BATREQ=y CONFIG_BAT_CYCLE=y CONFIG_BAT_PLATFORM=app_win64r",
"CONFIG_LUM": false,
"ARCH_CPU": "X86",
"BUILDTYPE_DEBUG": false,
"_RELEASE": true,
"_RELEASE_LEVEL": 2,
"CONFIG_BUILD_DATE": "13-Dec-19 16:38:15",
"ZON_VERSION": "1.160.573",
"ZON_VERSION_1": 1,
"ZON_VERSION_2": 160,
"ZON_VERSION_3": 573,
"ZON_COPYRIGHT_YEAR": "2019",
"SVC_EXE": "hola_svc.exe",
"SVC_EXE_ANDROID": "libhola_svc.so",
"UPDATER_EXE": "hola_updater.exe",
"NET_SVC_EXE": "net_svc.exe",
"NET_SVC_ZIP": "net_svc-x64-1.160.573.zip",
"NET_SVC_ZIP_PDB": "net_svc-x64-1.160.573-pdb.zip",
"SVC_AGENTS_POOL": "198.15.118.142:22224:zagent876,66.85.185.88:22224:zagent877,66.85.131.68:22224:zagent1253,107.170.54.54:22224:zagent779,108.170.8.157:22224:zagent1251",
"BEXT_CHROME_ID_REL": "pnknnijoleibcpmkdcooclmnjmmdhgbg",
"BEXT_CHROME_CWS_ID_REL": "gkojfkhlekighikafcpjkiklfbnlmeio",
"BEXT_OPERA_ADDONS_ID_REL": "ekmmelpnmfdegjhnmadddcfjcahpajnm",
"BEXT_FF_ID_REL_SIGNED": "ff_ext@hola.org",
"BEXT_FF_ORIGIN_SIGNED": "resource://ff_ext-at-hola-dot-org",
"BEXT_FF_ID_REL": "jid1-4P0kohSJxU1qGg@jetpack",
"BEXT_FF_ORIGIN": "resource://jid1-4p0kohsjxu1qgg-at-jetpack",
"CONFIG_MP_CHROME": false,
"CONFIG_MP_OPERA": true,
"BEXT": 1,
"BEXT_VA_CHROME_ID_REL": "chgpmaaockmdehmidghebcjafhihlgha",
"HOLA_ADBLOCK_ID_REL": "lalfpjdbhpmnhfofkckdpkljeilmogfl"
};
if (typeof module=='object'&&module&&module.exports)
    module.exports = zon_config;else if (typeof define=='function') define(zon_config);
